# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goT8OGDOFHJEk73La3x3tT9m5GQunfk_
"""

import os, warnings, numpy as np, pandas as pd
import matplotlib.pyplot as plt, matplotlib.gridspec as gridspec
from scipy.stats import norm as sp_norm, chi2 as sp_chi2, gaussian_kde
from scipy import stats as sp_stats
warnings.filterwarnings('ignore')
import yfinance as yf

W_CALIB, W_EVENT = 100, 15
START_DATE, END_DATE = '1999-01-01', '2025-12-31'
MIN_COMPLETENESS = 0.995
K_FACTORS = 4
ALPHA = 0.01
Z_ALPHA = float(sp_norm.ppf(1.0 - ALPHA))
ALPHA_TEST = 0.05
IS_END_DATE, OOS_START_DATE = '2012-12-31', '2013-01-01'
KAPPA_GRID = [0.010,0.020,0.030,0.040,0.050,0.060,0.080,0.100]
KAPPA_STAR = 0.030
SPX_TICKER = '^GSPC'
RV_WINDOW = 15

SECTOR_TICKERS = {
    'Large-Cap Technology':    ['AAPL','MSFT','INTC','IBM','CSCO','HPQ','ORCL','TXN','GLW','STX'],
    'Semiconductors':          ['QCOM','ADI','MU','KLAC','LRCX','NVDA','AMAT','TER','SWKS','NXPI'],
    'Enterprise Software':     ['ADBE','INTU','ADSK','PEGA','SNPS','CDNS','PTC','MANH','PRGS','FICO'],
    'Large Banks':             ['JPM','BAC','WFC','C','USB','PNC','STT','KEY','MTB','FITB'],
    'Insurance':               ['BRK-B','AIG','MET','PRU','AFL','ALL','CB','TRV','HIG','LNC'],
    'Pharmaceuticals':         ['JNJ','PFE','MRK','AMGN','GILD','BMY','LLY','BIIB','ABT','AZN'],
    'Biotechnology':           ['VRTX','REGN','ILMN','INCY','QGEN','BMRN','NBIX','EXEL','IONS','RARE'],
    'Consumer Retail':         ['WMT','TGT','COST','HD','LOW','KR','CVS','TJX','M','KSS'],
    'Automotive & Parts':      ['F','HOG','BWA','AZO','ORLY','AAP','GPC','LKQ','MGA','LEA'],
    'Energy':                  ['XOM','CVX','SLB','HAL','OXY','DVN','APA','COP','VLO','PSX'],
    'Utilities':               ['NEE','DUK','SO','AEP','EXC','D','XEL','ETR','ED','PCG'],
    'Materials':               ['APD','ECL','SHW','FCX','NEM','VMC','MLM','PPG','IFF','RPM'],
    'Aerospace & Defense':     ['BA','LMT','GD','NOC','TXT','HWM','HEI','TDG','TDY','RTX'],
    'Transportation':          ['UPS','FDX','UNP','CSX','NSC','LUV','ALK','CHRW','EXPD','LSTR'],
    'Real Estate (REITs)':     ['PLD','SPG','VNO','PSA','O','AVB','EQR','ESS','KIM','NNN'],
    'Consumer Staples':        ['PG','KO','PEP','PM','MO','CL','GIS','CAG','CPB','HSY'],
    'Media & Entertainment':   ['DIS','CMCSA','OMC','EA','NYT','SIRI','FOXA','NWS','LYV','IMAX'],
    'Telecom':                 ['T','VZ','SATS','TDS','SHEN','LUMN','ATN','CCOI','TIGO','CABO'],
    'Healthcare Services':     ['UNH','CI','HUM','ELV','MOH','CNC','DVA','LH','DGX','HCA'],
    'Industrial Conglomerates':['GE','HON','MMM','ITW','DOV','PH','ROP','FLR','ROK','ETN'],
}
SF_CRISIS_PERIODS = [
    ('Dot-com\nCrash',   '2000-03-10', '2002-10-09'),
    ('GFC',              '2008-09-01', '2009-03-09'),
    ('Eurozone\nCrisis', '2011-07-01', '2011-11-25'),
    ('Oil Crash',        '2014-06-01', '2016-02-11'),
    ('COVID-19',         '2020-02-19', '2020-03-23'),
    ('Ukraine\nWar',     '2022-02-24', '2022-09-30'),
]
IS_CRISIS_PERIODS = [
    ('GFC 2008–09',       '2008-09-01', '2009-03-09'),
    ('Eurozone 2011',     '2011-07-01', '2011-11-25'),
]
OOS_CRISIS_PERIODS = [
    ('Oil Crash 2014–16', '2014-06-01', '2016-02-11'),
    ('Covid-19 2020',     '2020-02-19', '2020-03-23'),
    ('Ukraine 2022',      '2022-02-24', '2022-09-30'),
]
CRISIS_PERIODS = OOS_CRISIS_PERIODS

# ══════════════════ PART 1 — DATA & SF ══════════════════
def download_returns(sector_tickers, start, end, min_completeness=MIN_COMPLETENESS):
    all_tickers = list(dict.fromkeys(t for ts in sector_tickers.values() for t in ts))
    print(f"[Data] Downloading {len(all_tickers)} tickers | {start} → {end}")
    raw = yf.download(all_tickers, start=start, end=end, auto_adjust=True, progress=True, threads=True)
    prices = raw['Close'] if isinstance(raw.columns, pd.MultiIndex) else raw
    log_ret = np.log(prices / prices.shift(1)).iloc[1:]
    completeness = log_ret.notna().mean()
    keep = completeness[completeness >= min_completeness].index.tolist()
    print(f"[Data] {len(keep)} / {len(all_tickers)} tickers passed completeness filter (≥ {min_completeness*100:.1f}%)")
    log_ret = log_ret[keep].ffill(limit=1).dropna()
    T, N = log_ret.shape
    print(f"[Data] Final matrix: {T:,} trading days × {N} assets\n")
    return log_ret

def choose_k_factors(returns, w_calib=W_CALIB, date_idx=None):
    N, T = returns.shape[1], len(returns)
    lam_mp = (1.0 + np.sqrt(N / W_EVENT)) ** 2
    if date_idx is None:
        date_idx = min(T - W_EVENT - 10, max(w_calib + W_EVENT, T // 2))
    R_c = returns.iloc[date_idx - w_calib: date_idx].values.T
    mu_c, sd_c = R_c.mean(axis=1, keepdims=True), R_c.std(axis=1, keepdims=True) + 1e-12
    R_c = (R_c - mu_c) / sd_c
    C_c = R_c @ R_c.T / w_calib
    eigs = np.sort(np.linalg.eigvalsh(C_c))[::-1]
    n_above = int((eigs > lam_mp).sum())
    k_use = max(1, min(n_above, 10))
    print(f"\n[SF-Scree] N={N} | W_event={W_EVENT} | λ_MP = {lam_mp:.4f}")
    print(f"[SF-Scree] Eigenvalues above λ_MP : {n_above}")
    print(f"[SF-Scree] Top-10 eigenvalues     : {eigs[:10].round(3).tolist()}")
    print(f"[SF-Scree] k selected             : {k_use}\n")
    n_plot = min(30, len(eigs))
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(range(1, n_plot + 1), eigs[:n_plot], 'o-', color='black', lw=1.5, ms=5, zorder=3)
    ax.axhline(lam_mp, color='#CC0000', ls='--', lw=1.3, label=f'λ_MP = {lam_mp:.2f}  (k = {k_use} above)')
    ax.axvline(k_use, color='#555555', ls=':', lw=1.2, label=f'k* = {k_use} factors removed')
    ax.set_xlabel('Eigenvalue Rank'); ax.set_ylabel('Eigenvalue')
    ax.set_title(f'Calibration Covariance Scree Plot — Factor Selection\nN={N} assets | W_calib={w_calib} days | λ_MP = {lam_mp:.2f} | k* = {k_use}')
    ax.legend(fontsize=9.5); ax.spines[['top','right']].set_visible(False); ax.grid(axis='y', ls='--', alpha=0.35)
    plt.tight_layout(); plt.show()
    return k_use, eigs

def compute_sf(returns, w_calib=W_CALIB, w_event=W_EVENT, k_factors=K_FACTORS):
    X, dates = np.ascontiguousarray(returns.values, dtype=np.float64), returns.index
    T, N = X.shape
    min_t = w_calib + w_event
    if T <= min_t: raise ValueError(f"Only {T} trading days; need > {min_t}.")
    lam_mp = (1.0 + np.sqrt(N / w_event)) ** 2
    n_out = T - min_t
    sf_vals = np.empty(n_out, dtype=np.float64)
    sf_dates = dates[min_t:]
    print(f"[SF] N={N} | λ_MP={lam_mp:.4f} | k_factors={k_factors} | computing {n_out:,} daily SF values …")
    for i in range(n_out):
        t = i + min_t
        R_c = X[t - min_t: t - w_event, :].T
        mu_c, sd_c = R_c.mean(axis=1, keepdims=True), R_c.std(axis=1, keepdims=True) + 1e-12
        R_c = (R_c - mu_c) / sd_c
        C_c = R_c @ R_c.T / w_calib
        _, vecs = np.linalg.eigh(C_c)
        V_k = vecs[:, -k_factors:]
        R_e = X[t - w_event: t, :].T
        R_r = R_e - V_k @ (V_k.T @ R_e)
        mu_r, sd_r = R_r.mean(axis=1, keepdims=True), R_r.std(axis=1, keepdims=True) + 1e-12
        R_r = (R_r - mu_r) / sd_r
        C_r = R_r @ R_r.T / w_event
        sf_vals[i] = np.linalg.eigvalsh(C_r)[-1] / lam_mp
        if i % 500 == 0 or i == n_out - 1:
            print(f"  [{i+1:>5}/{n_out}] date = {sf_dates[i].date()}  SF = {sf_vals[i]:.4f}")
    return pd.Series(sf_vals, index=sf_dates, name='SF')

def print_sf_report(sf, crisis_periods, k_factors=K_FACTORS):
    bar = '═' * 66
    n_lt1, n_gt1, n_gt2 = int((sf<1).sum()), int((sf>1).sum()), int((sf>2).sum())
    print(f'\n{bar}\n SYNCHRONISATION FACTOR — SUMMARY REPORT\n{bar}')
    print(f' Period        : {sf.index[0].date()} → {sf.index[-1].date()}')
    print(f' Trading days  : {len(sf):,}')
    print(f' k factors     : {k_factors} (market + {k_factors-1} sector factors)')
    print(f' Mean SF       : {sf.mean():.4f}')
    print(f' Median SF     : {sf.median():.4f}')
    print(f' Std deviation : {sf.std():.4f}')
    print(f' Min / Max     : {sf.min():.4f} / {sf.max():.4f}')
    print(f' Days SF < 1   : {n_lt1:,} ({n_lt1/len(sf)*100:.1f}%)  ← calm markets')
    print(f' Days SF > 1   : {n_gt1:,} ({n_gt1/len(sf)*100:.1f}%)  ← elevated co-movement')
    print(f' Days SF > 2   : {n_gt2:,} ({n_gt2/len(sf)*100:.1f}%)  ← high-risk regime')
    print(f'\n Crisis-Period Breakdown:')
    print(f'  {"Crisis":<28} {"Days":>5} {"Mean SF":>9} {"Max SF":>9}')
    print(f'  {"─"*56}')
    for label, cs, ce in crisis_periods:
        sub = sf[(sf.index >= cs) & (sf.index <= ce)]
        if len(sub):
            print(f'  {label.replace(chr(10)," "):<28} {len(sub):>5} {sub.mean():>9.4f} {sub.max():>9.4f}')
    print(bar + '\n')

# ══════════════════ PART 2 — HYPOTHESIS 1 ══════════════════
def _sample_acf(x, nlags=30):
    n = len(x); x_dm = x - x.mean(); c0 = np.dot(x_dm, x_dm) / n
    acf = np.empty(nlags)
    for k in range(1, nlags + 1):
        acf[k-1] = np.dot(x_dm[:n-k], x_dm[k:]) / (n * c0)
    return acf

def classify_regimes(sf, spx_ticker=SPX_TICKER, rv_window=RV_WINDOW, stress_pct=0.90):
    t0 = (sf.index[0] - pd.offsets.BDay(rv_window + 15)).strftime('%Y-%m-%d')
    t1 = (sf.index[-1] + pd.offsets.BDay(5)).strftime('%Y-%m-%d')
    print(f"\n[H1] Downloading SPX ({spx_ticker}) for regime classification …")
    raw = yf.download(spx_ticker, start=t0, end=t1, auto_adjust=True, progress=False)
    close = raw['Close'].iloc[:, 0] if isinstance(raw.columns, pd.MultiIndex) else raw['Close']
    spx_ret = np.log(close / close.shift(1)).dropna()
    rv = spx_ret.rolling(rv_window).std() * np.sqrt(252)
    rv_aligned = rv.reindex(sf.index).ffill(limit=1).dropna()
    threshold = rv_aligned.quantile(stress_pct)
    regime = (rv_aligned >= threshold).astype(int); regime.name = 'Regime'
    n_total, n_stress = len(regime), int(regime.sum()); n_calm = n_total - n_stress
    print(f"[H1] SPX 30-day RV threshold (90th pct): {threshold:.4f} ({threshold*100:.2f}% ann.)")
    print(f"[H1] Stress days : {n_stress:>5} ({n_stress/n_total*100:.2f}%)")
    print(f"[H1] Calm days   : {n_calm:>5} ({n_calm/n_total*100:.2f}%)")
    return regime

def compute_h1_stats(sf, regime, n_acf_lags=30):
    common = sf.index.intersection(regime.index)
    sf_all, reg = sf.loc[common], regime.loc[common]
    sf_calm, sf_stress = sf_all[reg==0], sf_all[reg==1]
    n_calm, n_stress = len(sf_calm), len(sf_stress)
    print(f"\n[H1] Aligned: {len(common):,} common dates (calm = {n_calm:,}, stress = {n_stress:,})")
    mean_c, mean_s = sf_calm.mean(), sf_stress.mean()
    std_c, std_s = sf_calm.std(ddof=1), sf_stress.std(ddof=1)
    p25_c, p25_s = sf_calm.quantile(0.25), sf_stress.quantile(0.25)
    med_c, med_s = sf_calm.median(), sf_stress.median()
    p75_c, p75_s = sf_calm.quantile(0.75), sf_stress.quantile(0.75)
    p95_c, p95_s = sf_calm.quantile(0.95), sf_stress.quantile(0.95)
    ks_stat, ks_pval = sp_stats.ks_2samp(sf_calm.values, sf_stress.values)
    t_stat, t_pval = sp_stats.ttest_ind(sf_stress.values, sf_calm.values, equal_var=False, alternative='greater')
    s_pool = np.sqrt(((n_stress-1)*std_s**2 + (n_calm-1)*std_c**2) / (n_stress+n_calm-2))
    cohens_d = (mean_s - mean_c) / s_pool
    d_label = 'small effect' if cohens_d<0.2 else 'small-medium effect' if cohens_d<0.5 else 'medium effect' if cohens_d<0.8 else 'large effect'
    acf_vals = _sample_acf(sf_all.values, nlags=n_acf_lags)
    acf1 = acf_vals[0]
    if 0 < acf1 < 1:
        half_life = np.log(0.5) / np.log(acf1); hl_label = f'half-life ≈ {half_life:.0f} days'
    else:
        half_life, hl_label = np.inf, 'half-life > sample length'
    return dict(sf_calm=sf_calm, sf_stress=sf_stress, n_calm=n_calm, n_stress=n_stress,
                mean_c=mean_c, mean_s=mean_s, std_c=std_c, std_s=std_s, p25_c=p25_c, p25_s=p25_s,
                med_c=med_c, med_s=med_s, p75_c=p75_c, p75_s=p75_s, p95_c=p95_c, p95_s=p95_s,
                ks_stat=ks_stat, ks_pval=ks_pval, t_stat=t_stat, t_pval=t_pval,
                cohens_d=cohens_d, d_label=d_label, acf=acf_vals, acf1=acf1,
                half_life=half_life, hl_label=hl_label)

def print_table3(r):
    def _pct(c, s): return f'+{(s-c)/c*100:.1f}%'
    def _pfmt(p): return '< 0.000001' if p<1e-6 else (f'{p:.6f}' if p<0.001 else f'{p:.4f}')
    bar = '═'*74
    print(f'\n{bar}\n TABLE 3 — H1 Results: Synchronisation Factor: Stress vs. Calm Regimes\n{bar}')
    print(f'  {"Metric":<26} {"Calm Regime":>13} {"Stress Regime":>13} {"Δ / Test Statistic":>18}')
    print(f'  {"─"*72}')
    rows = [
        ('Mean SF', f'{r["mean_c"]:.3f}', f'{r["mean_s"]:.3f}', _pct(r["mean_c"], r["mean_s"])),
        ('Std. Deviation', f'{r["std_c"]:.3f}', f'{r["std_s"]:.3f}', 'Greater dispersion'),
        ('25th Percentile', f'{r["p25_c"]:.3f}', f'{r["p25_s"]:.3f}', _pct(r["p25_c"], r["p25_s"])),
        ('Median', f'{r["med_c"]:.3f}', f'{r["med_s"]:.3f}', _pct(r["med_c"], r["med_s"])),
        ('75th Percentile', f'{r["p75_c"]:.3f}', f'{r["p75_s"]:.3f}', _pct(r["p75_c"], r["p75_s"])),
        ('95th Percentile', f'{r["p95_c"]:.3f}', f'{r["p95_s"]:.3f}', 'Fatter right tail'),
        ('N (days)', f'{r["n_calm"]:,}', f'{r["n_stress"]:,}', 'Top-10% SPX vol'),
        ('KS Statistic D', '—', '—', f'{r["ks_stat"]:.4f}'),
        ('KS p-value', '—', '—', _pfmt(r['ks_pval'])),
        ('Welch t-statistic', '—', '—', f'{r["t_stat"]:.3f}'),
        ('Welch p-value', '—', '—', _pfmt(r['t_pval'])),
        ("Cohen's d", '—', '—', f'{r["cohens_d"]:.3f} ({r["d_label"]})'),
        ('ACF(1)', '—', '—', f'{r["acf1"]:.3f} ({r["hl_label"]})'),
    ]
    for metric, calm, stress, delta in rows:
        print(f'  {metric:<26} {calm:>13} {stress:>13} {delta}')
    print(f"\n  Note. KS = Kolmogorov–Smirnov two-sample test (two-sided). Welch t-test\n"
          f"  allows for unequal variances (one-sided: H1 stress > calm).\n"
          f"  Cohen's d = standardised mean difference using pooled SD.\n"
          f"  ACF(1) estimated over the full SF series (biased estimator).")
    print(bar)
    a = 0.05
    rej_ks, rej_t = r['ks_pval']<a, r['t_pval']<a
    mean_d = r['mean_s'] - r['mean_c']; mean_pct = mean_d/r['mean_c']*100
    print(f'\n H1 VERDICT (α = {a}):\n  {"─"*50}')
    print(f'  KS test  → {"✓ REJECT H0" if rej_ks else "✗ Fail to reject H0"} (D = {r["ks_stat"]:.4f}, p = {_pfmt(r["ks_pval"])})')
    print(f'  Welch t  → {"✓ REJECT H0" if rej_t else "✗ Fail to reject H0"} (t = {r["t_stat"]:.3f}, p = {_pfmt(r["t_pval"])})')
    print(f'  Mean diff → +{mean_d:.3f} (+{mean_pct:.1f}% stress vs. calm)')
    if rej_ks and rej_t:
        print(f'\n  ✓ H1 CONFIRMED: SF is statistically significantly higher in stress regimes.\n  Both distributional and mean tests reject H0.')
    elif rej_t:
        print(f'\n  ⚠ PARTIAL: Welch t rejects H0 but KS does not.')
    else:
        print(f'\n  ✗ H1 NOT CONFIRMED at α = {a}.')
    print()

def plot_figure2(r, n_acf_lags=30):
    sf_calm, sf_stress, acf_vals = r['sf_calm'], r['sf_stress'], r['acf']
    lags = np.arange(1, n_acf_lags+1)
    fig = plt.figure(figsize=(14, 5.2))
    gs = gridspec.GridSpec(1, 2, figure=fig, wspace=0.30)
    ax_a, ax_b = fig.add_subplot(gs[0]), fig.add_subplot(gs[1])
    x_lo = min(sf_calm.min(), sf_stress.min())*0.90
    x_hi = max(sf_stress.max(), sf_calm.max())*1.08
    x_grid = np.linspace(max(x_lo,0), x_hi, 800)
    y_calm = gaussian_kde(sf_calm.values, bw_method='scott')(x_grid)
    y_stress = gaussian_kde(sf_stress.values, bw_method='scott')(x_grid)
    ax_a.plot(x_grid, y_calm, color='#1565C0', lw=2.0, label='Calm Regime', zorder=3)
    ax_a.plot(x_grid, y_stress, color='#B71C1C', lw=2.0, ls='--', label='Stress Regime', zorder=3)
    y_top = max(y_calm.max(), y_stress.max())*1.12
    ax_a.axvline(1.0, color='#333333', lw=1.0, ls=':', alpha=0.6, label='SF = 1 (MP Bound)')
    ax_a.axvline(r['mean_c'], color='#1565C0', lw=1.0, ls=':', alpha=0.7)
    ax_a.axvline(r['mean_s'], color='#B71C1C', lw=1.0, ls=':', alpha=0.7)
    ax_a.text(r['mean_c']+0.06, y_top*0.82, f'μ={r["mean_c"]:.3f}', color='#1565C0', fontsize=8, va='center')
    ax_a.text(r['mean_s']+0.06, y_top*0.70, f'μ={r["mean_s"]:.3f}', color='#B71C1C', fontsize=8, va='center')
    ax_a.set_xlim(max(x_lo,0), x_hi); ax_a.set_ylim(0, y_top)
    ax_a.set_xlabel('Synchronisation Factor (SF)'); ax_a.set_ylabel('Density')
    ax_a.set_title('Panel A. Distributional Shift', fontweight='bold')
    ax_a.legend(fontsize=9); ax_a.spines[['top','right']].set_visible(False); ax_a.grid(axis='y', ls='--', alpha=0.30)
    ax_b.bar(lags, acf_vals, color='#212121', width=0.65, zorder=3)
    ax_b.axhline(0.5, color='black', lw=1.1, ls='--', zorder=4, label='ACF = 0.5')
    ax_b.text(1, acf_vals[0]+0.015, f'{acf_vals[0]:.3f}', ha='center', va='bottom', fontsize=7.5)
    ax_b.text(n_acf_lags, acf_vals[-1]+0.015, f'{acf_vals[-1]:.3f}', ha='center', va='bottom', fontsize=7.5)
    ax_b.set_xlim(0.5, n_acf_lags+0.5); ax_b.set_ylim(0, min(1.18, max(acf_vals)+0.12))
    ax_b.set_xlabel('Lag (days)'); ax_b.set_ylabel('Autocorrelation Coefficient')
    ax_b.set_title('Panel B. Autocorrelation Function of SF', fontweight='bold')
    ax_b.set_xticks([1,5,10,15,20,25,30]); ax_b.legend(fontsize=9)
    ax_b.spines[['top','right']].set_visible(False); ax_b.grid(axis='y', ls='--', alpha=0.30)
    note = ('Note. Panel A: KDE of SF in calm (solid blue) and stress (dashed red) regimes. '
            'Dotted vertical line: SF = 1 (MP bound); dotted lines also mark regime means. '
            'Panel B: Sample ACF of SF at lags 1–30. Dashed line marks ACF = 0.5 (half-life).')
    fig.text(0.5, -0.04, note, ha='center', va='top', fontsize=8.5, style='italic', color='#333333')
    plt.tight_layout(rect=[0,0.04,1,1]); plt.show()
    return fig

def run_h1(sf, n_acf_lags=30, spx_ticker=SPX_TICKER, rv_window=RV_WINDOW, stress_pct=0.90):
    print('\n' + '═'*66)
    print(' HYPOTHESIS 1 — SF Distributional Test: Stress vs. Calm')
    print(' H0 : μ_SF_stress = μ_SF_calm')
    print(' H1 : μ_SF_stress > μ_SF_calm  (one-sided Welch t; also KS test)')
    print('═'*66)
    regime = classify_regimes(sf, spx_ticker=spx_ticker, rv_window=rv_window, stress_pct=stress_pct)
    results = compute_h1_stats(sf, regime, n_acf_lags=n_acf_lags)
    results['regime'] = regime
    print_table3(results)
    plot_figure2(results, n_acf_lags=n_acf_lags)
    return results

# ══════════════════ PART 3 — STAT TESTS ══════════════════
def kupiec_uc(hits, alpha=ALPHA):
    T, V = len(hits), int(hits.sum())
    if V == 0: return 0.0, 1.0
    if V == T: return np.nan, 0.0
    p_hat = V / T
    ll_H0 = V*np.log(alpha) + (T-V)*np.log(1.0-alpha)
    ll_H1 = V*np.log(p_hat) + (T-V)*np.log(1.0-p_hat)
    LR = -2.0*(ll_H0-ll_H1)
    return float(LR), float(1.0 - sp_chi2.cdf(LR, df=1))

def christoffersen_ind(hits):
    h = np.asarray(hits, dtype=int)
    n00 = int(((h[:-1]==0)&(h[1:]==0)).sum()); n01 = int(((h[:-1]==0)&(h[1:]==1)).sum())
    n10 = int(((h[:-1]==1)&(h[1:]==0)).sum()); n11 = int(((h[:-1]==1)&(h[1:]==1)).sum())
    eps = 1e-10
    p01 = np.clip(n01/max(n00+n01,1), eps, 1-eps); p11 = np.clip(n11/max(n10+n11,1), eps, 1-eps)
    pi = np.clip((n01+n11)/max(len(h)-1,1), eps, 1-eps)
    ll1 = n00*np.log(1-p01)+n01*np.log(p01)+n10*np.log(1-p11)+n11*np.log(p11)
    ll0 = (n00+n10)*np.log(1-pi)+(n01+n11)*np.log(pi)
    LR = float(max(-2.0*(ll0-ll1), 0.0))
    return LR, float(1.0 - sp_chi2.cdf(LR, df=1))

def christoffersen_cc(hits, alpha=ALPHA):
    LR_uc, _ = kupiec_uc(hits, alpha); LR_in, _ = christoffersen_ind(hits)
    LR_cc = (LR_uc if not np.isnan(LR_uc) else 0.0) + LR_in
    return LR_cc, float(1.0 - sp_chi2.cdf(LR_cc, df=2))

def basel_zone(p_kupiec, sig=ALPHA_TEST):
    return 'GREEN' if p_kupiec>sig else ('Yellow' if p_kupiec>0.001 else 'Red')

def _pf(p, dec=3):
    if p is None or not np.isfinite(p): return ' — '
    s = '***' if p<0.001 else '** ' if p<0.01 else '*  ' if p<0.05 else 'ns '
    return f'{p:.{dec}f}{s}'

# ══════════════════ PART 4 — VaR MODELS ══════════════════
def var_model_A(port, w=W_CALIB):
    sigma = port.rolling(w, min_periods=w).std()
    return (Z_ALPHA * sigma.shift(1)).rename('VaR_A')

def var_model_B(port, w=W_CALIB):
    q = port.rolling(w, min_periods=w).quantile(ALPHA)
    return (-q.shift(1)).rename('VaR_B')

def var_model_C(port, w=W_CALIB):
    """Model C — Filtered HS (EWMA, λ=0.94)."""
    ret = port.dropna(); n = len(ret)
    lam = 0.94
    h_arr = np.zeros(n)
    h_arr[0] = float(ret.values[:20].std())
    for i in range(1, n):
        h_arr[i] = np.sqrt(lam*h_arr[i-1]**2 + (1-lam)*ret.values[i-1]**2)
    h = pd.Series(h_arr, index=ret.index, name='h')
    print("  [C] EWMA volatility computed (λ = 0.94).")
    eps = (ret / h.clip(lower=1e-12)).rename('eps')
    h_full, eps_full = h.reindex(port.index), eps.reindex(port.index)
    eps_q = eps_full.rolling(w, min_periods=w).quantile(ALPHA).shift(1)
    return (h_full * (-eps_q)).rename('VaR_C')

def var_model_D(var_a, sf, N, w_evt=W_EVENT, kappa=None):
    if kappa is None: kappa = KAPPA_STAR
    lam_mp = (1.0 + np.sqrt(N / w_evt)) ** 2
    sf_aln = sf.reindex(var_a.index).ffill(limit=3)
    excess = np.maximum(0.0, sf_aln.values - 1.0)
    adj = 1.0 + kappa * lam_mp * excess
    return pd.Series(var_a.values * adj, index=var_a.index, name='VaR_D')

# ══════════════════ PART 5 — BACKTEST ENGINE ══════════════════
def run_backtest(port_ret, var_pred, label='Model', alpha=ALPHA, verbose=True):
    idx = port_ret.index.intersection(var_pred.index)
    r, v = port_ret.loc[idx], var_pred.loc[idx]
    ok = v.notna() & r.notna(); r, v = r[ok], v[ok]
    hits = (r < -v).astype(int).values
    T, V = len(hits), int(hits.sum())
    rate = V/T if T>0 else np.nan
    LR_uc, p_uc = kupiec_uc(hits, alpha)
    LR_in, p_in = christoffersen_ind(hits)
    LR_cc, p_cc = christoffersen_cc(hits, alpha)
    zn = basel_zone(p_uc)
    loss_on_viol = -r.values[hits==1]
    es = float(loss_on_viol.mean()) if V>0 else np.nan
    if verbose:
        print(f"  {label:<38} V={V:>4}  rate={rate*100:.2f}%  Kupiec-p={p_uc:.4f}  [{zn}]")
    return dict(label=label, T=T, V=V, rate=rate, LR_uc=LR_uc, p_uc=p_uc, LR_in=LR_in, p_in=p_in,
                LR_cc=LR_cc, p_cc=p_cc, zn=zn, es=es, hits=pd.Series(hits, index=v.index), ret=r, var=v)

def run_crisis_backtest(port_ret, var_pred, crises, alpha=ALPHA):
    results = []
    for lbl, cs, ce in crises:
        mask = (port_ret.index>=cs)&(port_ret.index<=ce)
        r_c = port_ret[mask]; v_c = var_pred.reindex(r_c.index)
        ok = v_c.notna() & r_c.notna(); r_c, v_c = r_c[ok], v_c[ok]
        T = len(r_c)
        V = int((r_c < -v_c).sum()) if T>0 else 0
        hits = (r_c < -v_c).astype(int).values if T>0 else np.array([0])
        _, p = kupiec_uc(hits, alpha)
        results.append(dict(label=lbl, days=T, V=V, rate=V/T if T>0 else np.nan, p_uc=p))
    return results

# ══════════════════ PART 6 — κ GRID SEARCH ══════════════════
def run_kappa_grid(port, var_a, sf, N, grid=KAPPA_GRID, date_start=None, date_end=None, period_label='Full Sample'):
    lam_mp = (1.0 + np.sqrt(N / W_EVENT)) ** 2
    sf_aln = sf.reindex(var_a.index).ffill(limit=3)
    rows = []
    print(f"\n[κ-Grid] Period: {period_label} | λ_MP = {lam_mp:.4f}")
    if date_start or date_end:
        lo = pd.Timestamp(date_start) if date_start else port.index[0]
        hi = pd.Timestamp(date_end) if date_end else port.index[-1]
        port_slice = port.loc[(port.index>=lo)&(port.index<=hi)]
        var_a_sl = var_a.loc[(var_a.index>=lo)&(var_a.index<=hi)]
        sf_sl = sf_aln.loc[(sf_aln.index>=lo)&(sf_aln.index<=hi)]
        print(f"[κ-Grid] Date range: {lo.date()} → {hi.date()} ({len(port_slice):,} trading days)")
    else:
        port_slice, var_a_sl, sf_sl = port, var_a, sf_aln
        print(f"[κ-Grid] Date range: full series ({len(port_slice):,} trading days)")
    for kap in grid:
        excess = np.maximum(0.0, sf_sl.values - 1.0)
        adj = 1.0 + kap*lam_mp*excess
        vk = pd.Series(var_a_sl.values * adj, index=var_a_sl.index)
        res = run_backtest(port_slice, vk, label=f'κ={kap:.3f}', verbose=False)
        rows.append({'kappa': kap, 'V': res['V'], 'rate': res['rate'], 'LR_uc': res['LR_uc'],
                     'p_uc': res['p_uc'], 'es': res['es']})
        star = ' ← passes Kupiec 5%' if res['p_uc']>ALPHA_TEST else ''
        print(f"    κ={kap:.3f}  V={res['V']:>3}  rate={res['rate']*100:.3f}%  "
              f"Kupiec-LR={res['LR_uc']:.2f}  p={res['p_uc']:.4f}  ES={res['es']*100:.3f}%{star}")
    return pd.DataFrame(rows)

def select_kappa_star(grid_df, alpha_test=ALPHA_TEST, grid=KAPPA_GRID):
    eligible = grid_df[grid_df['rate'] < ALPHA].copy()
    if len(eligible) == 0:
        best_row = grid_df.loc[grid_df['rate'].idxmin()]
        kstar = float(best_row['kappa'])
        print(f"\n[κ*] ⚠ WARNING: No κ in grid achieves rate < {ALPHA*100:.1f}%.")
        print(f"[κ*]   Falling back to lowest-rate κ = {kstar:.3f}  (rate = {best_row['rate']*100:.3f}%,  Kupiec p = {best_row['p_uc']:.4f})")
        print(f"[κ*]   Consider expanding KAPPA_GRID upper bound.")
        return kstar, False
    best_idx = eligible['p_uc'].idxmax()
    best_row = eligible.loc[best_idx]
    kstar = float(best_row['kappa']); found = bool(best_row['p_uc'] > alpha_test)
    print(f"\n[κ*] κ selected (rate < {ALPHA*100:.1f}% ∩ highest Kupiec p) on IS grid:")
    print(f"[κ*]   κ* = {kstar:.3f}  |  IS violation rate = {best_row['rate']*100:.3f}%  |  Kupiec p = {best_row['p_uc']:.4f}")
    if found:
        print(f"[κ*]   ✓ Rate < 1% and Kupiec H0 not rejected at {alpha_test} — valid IS coverage.")
    else:
        print(f"[κ*]   ✓ Rate < 1% satisfied, but Kupiec p = {best_row['p_uc']:.4f} < {alpha_test}.")
        print(f"[κ*]     Coverage is sub-target but test power may be limited by IS sample size.")
    return kstar, found

# ══════════════════ PART 7 — TABLES AND FIGURES ══════════════════
def print_table_a1(grid_df, kappa_star_is, period_label='IS (1999–2012)'):
    bar = '═'*82
    print(f'\n{bar}\n  TABLE A.1 — IS Calibration Grid — Model D (Eigenvalue-Adjusted VaR)\n  Period: {period_label}\n{bar}')
    print(f'  {"kappa":>10} {"Violations":>12} {"Rate %":>8} {"Kupiec LR":>10} {"Kupiec p":>14} {"ES viol days":>13}')
    print(f'  {"─"*79}')
    for _, row in grid_df.iterrows():
        sel = ' ← κ* SELECTED (min κ passing Kupiec)' if abs(row['kappa']-kappa_star_is)<1e-6 else ''
        print(f'  {row["kappa"]:>10.3f} {row["V"]:>12.0f} {row["rate"]*100:>8.3f} '
              f'{row["LR_uc"]:>10.2f} {_pf(row["p_uc"]):>14} {row["es"]*100:>13.3f}%{sel}')
    print(f'\n  Note. κ* = {kappa_star_is:.3f} is the minimum κ where Kupiec H0 is not rejected at the 5% level on the IS period.')
    print(f'  This κ is locked before the OOS window is examined.')
    print(f'  Conservation-of-Risk: as κ ↑, violation rate ↓ but ES on violation days ↑.')
    print(bar + '\n')

def print_table5_oos(bt_oos, kappa_star_is, oos_start=OOS_START_DATE, oos_end=END_DATE):
    T = bt_oos['A']['T']; bar = '═'*118; sep = '─'*116
    print(f'\n{bar}\n  TABLE 5 — H2 Out-of-Sample Backtest Results — Four VaR Models at 99% Confidence Level')
    print(f'  OOS Period: {oos_start} → {oos_end} | Trading days: {T:,} | Expected violations at 1%: {T*ALPHA:.0f}')
    print(f'  κ* = {kappa_star_is:.3f} locked from IS calibration (1999–2012); not re-estimated on OOS data.')
    print(bar)
    print(f'  {"Model":<40} {"Viol.":>5} {"Rate%":>6} {"Target":>7}  {"Kupiec UC p":>11} {"Christo. Ind p":>14} {"Christo. CC p":>13}  {"Basel":>7} {"ES":>9}')
    print(f'  {sep}')
    names = {'A':'A — Normal VaR', 'B':'B — Historical Sim', 'C':'C — Filtered HS (EWMA, λ=0.94)',
             'D':f'D — Eigenvalue-Adj (κ*={kappa_star_is:.3f}, IS-locked)'}
    for key in 'ABCD':
        r = bt_oos[key]; zn = r['zn']
        zs = f'{"GREEN":^7}' if zn=='GREEN' else f'{zn:^7}'
        print(f'  {names[key]:<40} {r["V"]:>5} {r["rate"]*100:>6.2f} {"1.00":>7}  '
              f'{_pf(r["p_uc"]):>11} {_pf(r["p_in"]):>14} {_pf(r["p_cc"]):>13}  {zs:>7} {r["es"]:>9.5f}')
    print(f'\n  Note. *** p < 0.001; ** p < 0.01; * p < 0.05; ns = not significant.')
    print(f'  ES = average loss on violation days as a proportion of portfolio value.')
    print(f'  All results are out-of-sample. κ was selected on IS data (Table A.1)')
    print(f'  and held fixed; this table was not seen during κ selection.')
    print(f'  Kupiec UC: H0 = correct coverage.')
    print(f'  Christoffersen Ind: H0 = violations are serially independent.')
    print(f'  Christoffersen CC: joint test of UC + Independence.')
    print(bar)
    d, a = bt_oos['D'], bt_oos['A']
    print(f'\n H2 VERDICT (α = {ALPHA_TEST}) — OOS WINDOW:\n  {"─"*60}')
    for key in 'ABCD':
        r = bt_oos[key]; ok = r['zn']=='GREEN'
        print(f'  {names[key]:<50}: {"✓ PASS (Green)" if ok else "✗ FAIL"}  rate = {r["rate"]*100:.2f}%  Kupiec p = {r["p_uc"]:.4f}')
    if d['zn']=='GREEN':
        reduc = (a['V']-d['V'])/a['V']*100 if a['V']>0 else 0.0
        rate_imp = (a['rate']-d['rate'])/a['rate']*100 if a['rate']>0 else 0.0
        print(f'\n  ✓ H2 CONFIRMED (OOS): Model D achieves Basel GREEN.')
        print(f'    Violations reduced by {reduc:.1f}% ({a["V"]} → {d["V"]}).')
        print(f'    Violation rate improvement: {rate_imp:.1f}% ({a["rate"]*100:.2f}% → {d["rate"]*100:.2f}%).')
        print(f'    κ* was determined exclusively from IS data → no look-ahead bias.')
    else:
        print(f'\n  ✗ H2 NOT CONFIRMED on OOS data at α = {ALPHA_TEST}.')
    print()

def print_table6_oos(crisis_A, crisis_D, kappa_star_is, period_label='OOS (2013–2025)'):
    bar = '═'*100
    print(f'\n{bar}\n  TABLE 6 — OOS Crisis-Period VaR Violation Rates — Normal VaR (A) vs. Eigenvalue-Adj (D)')
    print(f'  Period: {period_label} | κ* = {kappa_star_is:.3f} (IS-locked)\n{bar}')
    print(f'  {"Crisis":<25} {"Days":>5}  {"A:Viol":>6} {"A:Rate%":>8} {"A:Kupiec p":>12}  {"D:Viol":>6} {"D:Rate%":>8} {"D:Kupiec p":>12}')
    print(f'  {"─"*96}')
    for ca, cd in zip(crisis_A, crisis_D):
        if ca['days']==0:
            print(f'  {ca["label"]:<25} {"(no data)":>5}'); continue
        ra = f'{ca["rate"]*100:.2f}' if not np.isnan(ca['rate']) else '—'
        rd = f'{cd["rate"]*100:.2f}' if not np.isnan(cd['rate']) else '—'
        print(f'  {ca["label"]:<25} {ca["days"]:>5}  {ca["V"]:>6} {ra:>8} {_pf(ca["p_uc"]):>12}  {cd["V"]:>6} {rd:>8} {_pf(cd["p_uc"]):>12}')
    print(f'\n  Note. *** p < 0.001; ** p < 0.01; * p < 0.05.')
    print(f'  All three crises fall within the OOS window; κ was not tuned on these dates.')
    print(f'  COVID-19: SF detects endogenous latent co-movement;')
    print(f'  exogenous shocks outside that scope will still show high violation rates.')
    print(bar + '\n')

def plot_figure4(bt, kappa_star_is, period_label='OOS'):
    keys = ['A','B','C','D']
    xlbls = ['Model A\nNormal VaR', 'Model B\nHistorical Sim', 'Model C\nFiltered HS\n(EWMA, λ=0.94)',
             f'Model D\nEigenvalue-Adj\n(κ*={kappa_star_is:.3f}, IS-locked)']
    rates = [bt[k]['rate']*100 for k in keys]; zones = [bt[k]['zn'] for k in keys]
    colors = ['#555555' if z!='GREEN' else '#888888' for z in zones]
    fig, ax = plt.subplots(figsize=(10, 6.5))
    x = np.arange(len(keys))
    bars = ax.bar(x, rates, width=0.52, color=colors, zorder=3, edgecolor='white', lw=0.5)
    for bar, rate, zon in zip(bars, rates, zones):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.04, f'{rate:.2f}%\n(Basel: {zon})',
                ha='center', va='bottom', fontsize=9.5, fontweight='bold')
    ax.axhline(1.00, color='black', lw=1.5, ls='--', zorder=4, label='Target: 1.00% (Basel Green Ceiling)')
    ax.set_xlim(-0.6, len(keys)-0.4); ax.set_ylim(0, max(rates)*1.35)
    ax.set_xticks(x); ax.set_xticklabels(xlbls, fontsize=10.5)
    ax.set_ylabel(f'VaR Violation Rate (%) — {period_label}')
    ax.set_title(f'VaR Violation Ratios — {period_label} ({bt["A"]["T"]:,} Trading Days), α = 0.01\n'
                 f'(99% Confidence Level | κ* = {kappa_star_is:.3f} locked from IS)')
    ax.legend(fontsize=9.5); ax.grid(axis='y', ls='--', alpha=0.35, zorder=1)
    ax.spines[['top','right']].set_visible(False)
    note = (f'Note. VaR violation ratios for {period_label} ({bt["A"]["T"]:,} trading days), α = 0.01. Dashed line = 1.00% target.\n'
            f'κ* = {kappa_star_is:.3f} selected on IS data (1999–2012) and locked before OOS evaluation.')
    fig.text(0.5, -0.01, note, ha='center', va='top', fontsize=8.5, style='italic', color='#333333')
    plt.tight_layout(rect=[0,0.04,1,1]); plt.show()
    return fig

def plot_figure5(grid_df, kappa_star_is):
    kappas, rates, es_pct = grid_df['kappa'].values, grid_df['rate'].values*100, grid_df['es'].values*100
    fig, ax1 = plt.subplots(figsize=(9.5, 5.5)); ax2 = ax1.twinx()
    l1, = ax1.plot(kappas, rates, 'o-', color='black', lw=1.8, ms=6.5, zorder=3, label='Violation Rate (%)')
    ax1.axhline(1.0, color='black', lw=0.9, ls='--', zorder=2, label='1% Target')
    ax1.axvline(kappa_star_is, color='black', lw=0.9, ls=':', zorder=2, label=f'κ* = {kappa_star_is:.3f} (IS-selected)')
    l2, = ax2.plot(kappas, es_pct, 's--', color='#555555', lw=1.5, ms=6, zorder=3, label='Avg ES on Violation Days (%)')
    try:
        star_idx = list(grid_df['kappa'].round(6)).index(round(kappa_star_is, 6))
        ax1.annotate(f'κ* = {kappa_star_is:.3f}\n(IS-selected)', xy=(kappa_star_is, rates[star_idx]),
                     xytext=(kappa_star_is+0.005, rates[star_idx]+0.10), fontsize=8.5, ha='left',
                     arrowprops=dict(arrowstyle='->', lw=0.8, color='black'))
    except ValueError: pass
    ax1.set_xlabel('Calibration Parameter κ'); ax1.set_ylabel('Violation Rate (%)')
    ax2.set_ylabel('Expected Shortfall on Violation Days (%)')
    ax1.set_title(f'Conservation-of-Risk Property — κ Sensitivity Analysis\n'
                  f'IS Calibration Period (1999–2012) | Model D: Eigenvalue-Adjusted VaR')
    lines = [l1, l2, plt.Line2D([0],[0], color='black', lw=0.9, ls='--'), plt.Line2D([0],[0], color='black', lw=0.9, ls=':')]
    lbls = ['Violation Rate (%)', 'Avg ES on Violation Days (%)', '1% Target', f'κ* = {kappa_star_is:.3f} (IS-selected)']
    ax1.legend(lines, lbls, loc='center right', fontsize=9)
    ax1.grid(axis='y', ls='--', alpha=0.35, zorder=1)
    ax1.spines[['top']].set_visible(False); ax2.spines[['top']].set_visible(False)
    note = (f'Note. IS calibration grid for Model D (1999–2012). Left axis: violation rate (%). '
            f'Right axis: expected shortfall on violation days (%).')
    fig.text(0.5, -0.02, note, ha='center', va='top', fontsize=8.5, style='italic', color='#333333')
    plt.tight_layout(rect=[0,0.08,1,1]); plt.show()
    return fig

def plot_figure6(crisis_A, crisis_D, kappa_star_is, period_label='OOS (2013–2025)'):
    labels = [c['label'] for c in crisis_A]
    rates_A = [c['rate']*100 if (c['days']>0 and not np.isnan(c['rate'])) else 0 for c in crisis_A]
    rates_D = [c['rate']*100 if (c['days']>0 and not np.isnan(c['rate'])) else 0 for c in crisis_D]
    n, w = len(labels), 0.33; x = np.arange(n)
    fig, ax = plt.subplots(figsize=(12, 6.5))
    bA = ax.bar(x-w/2, rates_A, width=w, color='#444444', label='Normal VaR (Model A)', zorder=3, edgecolor='white', lw=0.4)
    bD = ax.bar(x+w/2, rates_D, width=w, color='#999999', label=f'Eigenvalue-Adjusted VaR (Model D, κ*={kappa_star_is:.3f})', zorder=3, edgecolor='white', lw=0.4)
    for bar_arr, rts in [(bA, rates_A), (bD, rates_D)]:
        for bar, rate in zip(bar_arr, rts):
            if rate>0:
                ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.15, f'{rate:.2f}%', ha='center', va='bottom', fontsize=7.8, fontweight='bold')
    ax.axhline(1.00, color='black', lw=1.5, ls='--', label='Target: 1.00%', zorder=4)
    ax.axhline(3.60, color='#444444', lw=0.9, ls=':', alpha=0.65, label='Basel Yellow Threshold (3.60%)', zorder=2)
    y_ceil = max(max(rates_A), max(rates_D))*1.28 if (rates_A or rates_D) else 5.0
    ax.set_xlim(-0.65, n-0.35); ax.set_ylim(0, max(y_ceil, 5.0))
    ax.set_xticks(x); ax.set_xticklabels(labels)
    ax.set_ylabel('VaR Violation Rate (%)')
    ax.set_title(f'OOS VaR Violation Rates Across Crisis Periods — {period_label}\n'
                 f'(99% Confidence Level; Target = 1.00% | κ* = {kappa_star_is:.3f} IS-locked)')
    ax.legend(fontsize=9); ax.grid(axis='y', ls='--', alpha=0.35, zorder=1)
    ax.spines[['top','right']].set_visible(False)
    note = (f'Note. OOS VaR violation rates during three OOS market crises for Normal VaR (Model A, dark gray)\n'
            f'and Eigenvalue-Adjusted VaR (Model D, light gray). κ* = {kappa_star_is:.3f} was selected on IS data (1999–2012) and locked.\n'
            f'The dashed line marks the 1% target. The dotted line marks the Basel Yellow Zone Threshold (3.60%).')
    fig.text(0.5, -0.04, note, ha='center', va='top', fontsize=8.5, style='italic', color='#333333')
    plt.tight_layout(rect=[0,0.06,1,1]); plt.show()
    return fig

# ══════════════════ PART 8 — HYPOTHESIS 2 (IS→OOS) ══════════════════
def run_h3(sf, returns, is_end=IS_END_DATE, oos_start=OOS_START_DATE):
    print('\n' + '═'*66)
    print(' HYPOTHESIS 3 — VaR Backtesting (Two-Stage IS/OOS Pipeline)')
    print(f' IS  : {START_DATE} → {is_end}')
    print(f' OOS : {oos_start}  → {END_DATE}')
    print(' H0 : VaR_adj violation rate ≥ α  (model inadequate)')
    print(' H1 : VaR_adj passes Basel Green standard (OOS)')
    print('═'*66)
    N = returns.shape[1]
    lam_mp = (1.0 + np.sqrt(N/W_EVENT))**2
    print(f"\n[H3] Assets: N = {N} | λ_MP = {lam_mp:.4f} (W_event = {W_EVENT}) | Z_α = {Z_ALPHA:.4f}")
    port = returns.mean(axis=1).rename('Portfolio')
    mu_a, sig_a = port.mean()*252, port.std()*np.sqrt(252)
    print(f"[H3] Portfolio: annualised μ = {mu_a:.2%}  σ = {sig_a:.2%} ({len(port):,} trading days total)")
    print("\n[H3] Building VaR models on full series …")
    va = var_model_A(port);  print("  Model A (Normal VaR) done.")
    vb = var_model_B(port);  print("  Model B (Historical Simulation) done.")
    vc = var_model_C(port);  print("  Model C (Filtered HS / EWMA, λ=0.94) done.")
    print(f"\n{'─'*66}\n STAGE 1 — IS Calibration ({START_DATE} → {is_end})\n{'─'*66}")
    is_grid_df = run_kappa_grid(port, va, sf, N=N, grid=KAPPA_GRID, date_start=START_DATE, date_end=is_end,
                                period_label=f'IS ({START_DATE} → {is_end})')
    kappa_star_is, kstar_found = select_kappa_star(is_grid_df, ALPHA_TEST)
    global KAPPA_STAR
    KAPPA_STAR = kappa_star_is
    print_table_a1(is_grid_df, kappa_star_is, period_label=f'IS ({START_DATE} → {is_end})')
    plot_figure5(is_grid_df, kappa_star_is)
    print(f"\n[H3] IS crisis-period check (diagnostic) …")
    vd_is = var_model_D(va, sf, N=N, kappa=kappa_star_is)
    is_crisis_A = run_crisis_backtest(port, va, IS_CRISIS_PERIODS)
    is_crisis_D = run_crisis_backtest(port, vd_is, IS_CRISIS_PERIODS)
    print(f"  IS crisis results (informational — κ was optimised on IS):")
    for ca, cd in zip(is_crisis_A, is_crisis_D):
        ra = f'{ca["rate"]*100:.2f}%' if ca['days']>0 else '(no data)'
        rd = f'{cd["rate"]*100:.2f}%' if cd['days']>0 else '(no data)'
        print(f"    {ca['label']:<25} A:{ra}  D:{rd}")
    print(f"\n{'─'*66}\n STAGE 2 — OOS Validation ({oos_start} → {END_DATE})\n κ* = {kappa_star_is:.3f} LOCKED — not re-estimated\n{'─'*66}")
    oos_mask = (port.index >= oos_start)
    port_oos, va_oos, vb_oos, vc_oos = port.loc[oos_mask], va.loc[oos_mask], vb.loc[oos_mask], vc.loc[oos_mask]
    vd_full = var_model_D(va, sf, N=N, kappa=kappa_star_is)
    vd_oos = vd_full.loc[oos_mask]
    print(f"[H3] OOS window: {port_oos.index[0].date()} → {port_oos.index[-1].date()} ({len(port_oos):,} trading days)")
    print("\n[H3] OOS backtesting (κ locked) …")
    bt_oos = {
        'A': run_backtest(port_oos, va_oos, 'A — Normal VaR'),
        'B': run_backtest(port_oos, vb_oos, 'B — Historical Sim'),
        'C': run_backtest(port_oos, vc_oos, 'C — Filtered HS (EWMA, λ=0.94)'),
        'D': run_backtest(port_oos, vd_oos, f'D — Eigenvalue-Adj (κ*={kappa_star_is:.3f}, locked)'),
    }
    print_table5_oos(bt_oos, kappa_star_is, oos_start=oos_start, oos_end=END_DATE)
    plot_figure4(bt_oos, kappa_star_is, period_label=f'OOS ({oos_start}–{END_DATE})')
    print("[H3] OOS crisis-period backtesting …")
    oos_crisis_A = run_crisis_backtest(port_oos, va_oos, OOS_CRISIS_PERIODS)
    oos_crisis_D = run_crisis_backtest(port_oos, vd_oos, OOS_CRISIS_PERIODS)
    print_table6_oos(oos_crisis_A, oos_crisis_D, kappa_star_is, period_label=f'OOS ({oos_start}–{END_DATE})')
    plot_figure6(oos_crisis_A, oos_crisis_D, kappa_star_is, period_label=f'OOS ({oos_start}–{END_DATE})')
    return dict(bt_oos=bt_oos, port=port, port_oos=port_oos, va=va, vb=vb, vc=vc, vd_full=vd_full,
                va_oos=va_oos, vb_oos=vb_oos, vc_oos=vc_oos, vd_oos=vd_oos,
                oos_crisis_A=oos_crisis_A, oos_crisis_D=oos_crisis_D, is_grid_df=is_grid_df,
                kappa_star_is=kappa_star_is, kstar_found=kstar_found, N=N, lam_mp=lam_mp,
                bt=bt_oos, crisis_A=oos_crisis_A, crisis_D=oos_crisis_D)

# ══════════════════ PART 9 — MAIN ══════════════════
if __name__ == '__main__':
    print("=" * 66)
    print(" SYNCHRONISATION FACTOR — Latent Risk Detection (RMT)")
    print(f" Period  : {START_DATE} → {END_DATE}")
    print(f" IS      : {START_DATE} → {IS_END_DATE}")
    print(f" OOS     : {OOS_START_DATE} → {END_DATE}")
    print(f" W_CALIB = {W_CALIB} | W_EVENT = {W_EVENT} | K_FACTORS = {K_FACTORS}")
    print("=" * 66 + "\n")

    try:
        returns  # noqa: F821
        print(f"[Main] Using `returns` in scope: {returns.shape[1]} assets × {returns.shape[0]} days.")
    except NameError:
        returns = download_returns(SECTOR_TICKERS, START_DATE, END_DATE)

    try:
        sf  # noqa: F821
        print("[Main] Using `sf` already in scope.")
        k_factors = K_FACTORS
        print(f"[Main] Using K_FACTORS = {k_factors} from config.")
    except NameError:
        print("\n[Main] Step 1: Scree analysis to select k …")
        k_factors, _ = choose_k_factors(returns, w_calib=W_CALIB)
        print(f"[Main] Step 2: Computing SF with k = {k_factors} …")
        sf = compute_sf(returns, w_calib=W_CALIB, w_event=W_EVENT, k_factors=k_factors)

    print_sf_report(sf, SF_CRISIS_PERIODS, k_factors=k_factors)

    h1_results = run_h1(sf)

    h3_results = run_h3(sf, returns, is_end=IS_END_DATE, oos_start=OOS_START_DATE)


    kappa_star_is = h3_results['kappa_star_is']
    bt_oos = h3_results['bt_oos']

    print('\n' + '█'*66)
    print(' EXECUTIVE SUMMARY — THESIS RESULTS')
    print('█'*66)
    h1 = h1_results
    print('\n ── SF Calibration (Revision A) ────────────────────────────')
    print(f'  k factors removed : {k_factors}')
    print(f'  SF min / max      : {sf.min():.4f} / {sf.max():.4f}')
    n_lt1, n_gt2 = int((sf<1).sum()), int((sf>2).sum())
    print(f'  Days SF < 1       : {n_lt1:,} ({n_lt1/len(sf)*100:.1f}%) — calm markets')
    print(f'  Days SF > 2       : {n_gt2:,} ({n_gt2/len(sf)*100:.1f}%) — high-risk regime')
    print('\n ── κ Selection — IS / OOS Split (Revision B) ─────────────')
    print(f'  IS window  : {START_DATE} → {IS_END_DATE}')
    print(f'  OOS window : {OOS_START_DATE} → {END_DATE}')
    print(f'  κ* (IS-selected) : {kappa_star_is:.3f}  '
          f'({"min passing κ" if h3_results["kstar_found"] else "fallback — no κ passed"})')
    print(f'  κ* applied to OOS: LOCKED (not re-estimated)')
    print('\n ── Hypothesis 1: SF Distributional Test ──────────────────')
    print(f'  Stress mean SF : {h1["mean_s"]:.4f}  |  Calm mean SF : {h1["mean_c"]:.4f}')
    print(f'  Welch t-stat   : {h1["t_stat"]:.3f}  |  p-value      : {h1["t_pval"]:.6f}')
    print(f'  KS statistic   : {h1["ks_stat"]:.4f}  |  KS p-value  : {h1["ks_pval"]:.6f}')
    print(f'  Cohen\'s d      : {h1["cohens_d"]:.3f} ({h1["d_label"]})')
    print(f'  ACF(1)         : {h1["acf1"]:.3f}  |  {h1["hl_label"]}')
    rej_h1 = (h1['ks_pval']<ALPHA_TEST) and (h1['t_pval']<ALPHA_TEST)
    print(f'  VERDICT        : {"✓ H1 CONFIRMED" if rej_h1 else "✗ H1 not confirmed"} at α = {ALPHA_TEST}')
    print('\n ── Hypothesis 3: OOS VaR Backtesting Results ─────────────')
    print(f'  OOS period: {OOS_START_DATE} → {END_DATE} ({bt_oos["A"]["T"]:,} trading days)')
    print(f'  κ* = {kappa_star_is:.3f} (locked from IS — no look-ahead bias)')
    model_labels_oos = {'A':'A — Normal VaR', 'B':'B — Historical Sim', 'C':'C — Filtered HS (EWMA, λ=0.94)',
                        'D':f'D — Eigenvalue-Adj (κ*={kappa_star_is:.3f}, IS-locked)'}
    print(f'  {"Model":<44} {"Violations":>10} {"Rate%":>7} {"Kupiec p":>10} {"Basel":>8}')
    print(f'  {"─"*82}')
    for key in 'ABCD':
        r = bt_oos[key]; zn = r['zn']
        print(f'  {model_labels_oos[key]:<44} {r["V"]:>10} {r["rate"]*100:>7.2f} {r["p_uc"]:>10.4f} {zn:>8}')
    d_pass = bt_oos['D']['zn']=='GREEN'
    print(f'\n  VERDICT : {"✓ H3 CONFIRMED — Model D achieves Basel GREEN (OOS)." if d_pass else "✗ H3 not confirmed on OOS data."}')
    if d_pass:
        reduc = ((bt_oos['A']['V']-bt_oos['D']['V'])/bt_oos['A']['V']*100 if bt_oos['A']['V']>0 else 0.0)
        print(f'            Violations reduced by {reduc:.1f}% ({bt_oos["A"]["V"]} → {bt_oos["D"]["V"]}) vs. Normal VaR (OOS).')
    print('\n ── OOS Crisis-Period Summary (3 windows, 2013–2025) ──────')
    print(f'  {"Crisis":<25} {"Days":>5}  {"A:Rate%":>8}  {"D:Rate%":>8}  {"Improvement":>12}')
    print(f'  {"─"*65}')
    for ca, cd in zip(h3_results['oos_crisis_A'], h3_results['oos_crisis_D']):
        if ca['days']==0:
            print(f'  {ca["label"]:<25} {"(no data)":>5}'); continue
        ra = ca['rate']*100 if not np.isnan(ca['rate']) else 0.0
        rd = cd['rate']*100 if not np.isnan(cd['rate']) else 0.0
        imp = f'{ra-rd:+.2f}pp' if (ra>0 and rd>0) else '—'
        print(f'  {ca["label"]:<25} {ca["days"]:>5}  {ra:>8.2f}  {rd:>8.2f}  {imp:>12}')
    print('\n' + '█'*66)

    print('\n[Sanity] Running final consistency checks …')
    N_assets = returns.shape[1]
    lam_mp_final = (1.0 + np.sqrt(N_assets/W_EVENT))**2
    assert sf.notna().all(), "SF contains NaN values."
    assert np.isfinite(sf).all(), "SF contains Inf values."
    assert sf.min() > -0.5, "SF implausibly negative — check k."
    assert sf.max() < 100.0, "SF implausibly large — check inputs."
    va_chk = var_model_A(returns.mean(axis=1))
    assert (va_chk.dropna()>0).all(), "Model A VaR contains non-positive values."
    sf_test = pd.Series([0.5,1.0,1.5,2.0,3.0])
    excess = np.maximum(0.0, sf_test.values-1.0)
    adj = 1.0 + kappa_star_is*lam_mp_final*excess
    assert (np.diff(adj)>=0).all(), "Model D adjustment is not monotone in SF."
    for lbl, cs, ce in OOS_CRISIS_PERIODS:
        assert pd.Timestamp(cs) >= pd.Timestamp(OOS_START_DATE), f"OOS crisis '{lbl}' starts before OOS window!"
    for lbl, cs, ce in IS_CRISIS_PERIODS:
        assert pd.Timestamp(ce) <= pd.Timestamp(IS_END_DATE), f"IS crisis '{lbl}' ends after IS window!"
    assert h3_results['kappa_star_is'] == kappa_star_is, "κ* changed between IS calibration and OOS backtest — bug!"
    frac_lt1 = (sf<1).mean()
    if frac_lt1 < 0.05:
        print(f"  ⚠ Only {frac_lt1*100:.1f}% of days have SF < 1. Consider increasing k_factors beyond {k_factors}.")
    else:
        print(f'  ✓ SF < 1 on {frac_lt1*100:.1f}% of days (k-factor fix working).')
    print(f'  ✓ SF series finite and well-defined ({len(sf):,} obs).')
    print(f'  ✓ Model A VaR all positive.')
    print(f'  ✓ κ* = {kappa_star_is:.3f} selected from IS grid, locked for OOS.')
    print(f'  ✓ Model D adjustment monotone in SF (λ_MP = {lam_mp_final:.4f}).')
    print(f'  ✓ IS crises ({len(IS_CRISIS_PERIODS)}) all end ≤ {IS_END_DATE}.')
    print(f'  ✓ OOS crises ({len(OOS_CRISIS_PERIODS)}) all start ≥ {OOS_START_DATE}.')
    print(f'  ✓ k_factors = {k_factors} applied throughout.\n')

    print('═'*66)
    print(' THESIS PIPELINE COMPLETE')
    print(f' All revisions applied:')
    print(f'   [A] SF k-factor fix: k = {k_factors} factors removed (market + {k_factors-1} sector factors).')
    print(f'   [1] Model C → "Filtered HS (EWMA, λ=0.94)" throughout.')
    print(f'   [2] VAR / Granger / IRF / FEVD section removed entirely.')
    print(f'   [3] "Early warning" / causal language removed.')
    print(f'   [4] Dot-com row excluded from OOS crisis table (pre-OOS).')
    print(f'   [5] Limitations paragraph references actual OOS COVID results.')
    print(f'   [B] IS/OOS chronological split:')
    print(f'         IS  : {START_DATE} → {IS_END_DATE}  (κ calibration)')
    print(f'         OOS : {OOS_START_DATE} → {END_DATE}  (main results)')
    print(f'         κ*  = {kappa_star_is:.3f} (IS-selected, locked)')
    print(f'   [-] CAViaR, DQ test, AS-Z1, simulation study removed.')
    print('═'*66 + '\n')